### ISSUE TITLE
Textumbruch in 4.93

### ISSUE THREAD

**Issue by prenzlweb** [vanilla-thunder/bla-tinymce#13]
Hallo! An sich ein tolles Modul und Danke für die Arbeit. 
In der OXID 4.93 bricht der Text im Editor nicht in die nächste Zeile um. Es entsteht ein horizontaler Scrollbalken und der Text geht immer weiter nach rechts. Screenshot habe ich erstellt. Weiss nur nicht wie ich ihn hier posten soll...

**Comment by boremo** [comment]
Ich hatte dasselbe Problem und eine Lösung gefunden. In den eigenen Konfigurationsparameter bei den Moduleinstellungen habe ich folgendes eingetragen:
nowrap => false

**Comment by vanilla-thunder** [comment]
hallo,
es ist genau wie boremo schreibt, einfach nowrap => true ganz unten in "eigene Konfigurationsparameter" einfügen (ohne Anführungszeichen etc).

Viele Grüße
