### ISSUE TITLE
Eigener Konfigurationsparameter "toolbar" wird nicht übernommen

### ISSUE THREAD

**Issue by marcokernler** [vanilla-thunder/bla-tinymce#14]
Hallo,

ich habe gerade versucht die Dropdowns für die Schriftart und Schriftgröße über den Parameter "toolbar" in den Einstellungen des Moduls, wie folgt zu entfernen:

```php
toolbar => "undo redo | bold italic underline strikethrough | ...."
```

Leider ohne Erfolg. Wird der Parameter überhaupt beim Initialisieren beachtet?

**Comment by vanilla-thunder** [comment]
hallo,
ich habe in unseren Projekten nachgeschaut, aber den Parameter "toolbar" kann man in der Tat nicht direkt beeinflussen.
Ich stelle gerade ein Update für das Modul zusammen und baue einen Konfigurationsparameter für die Toolbar ein.

Viele Grüße
