### ISSUE TITLE
Deactivating of TinyMCE Plugins

### ISSUE THREAD

**Issue by pcaesar** [vanilla-thunder/bla-tinymce#17]
Hallo,
in der Backend-Konfiguration des Moduls (Ver. 2.0.1) lassen sich die Plugins nicht wie beschrieben deaktivieren oder genauer, sie lassen sich überhaupt nicht deaktivieren.
Beispiel:
colorpicker => false
Der Grund für die Fehlfunktion ist die Umwandlung von false in einen String beim Import der Konfiguration.
Lösung:
In Datei 'bla-tinymce/application/core/blatinymceoxviewconfig.php' Zeile 122 ändern:
return $value !== 'false';
Zusätzlich muss die Zeile 115 geändert werden: $aDefaultPlugins["legacyoutput"] = "false";

Danke für das tolle Modul!

Peter

**Comment by vanilla-thunder** [comment]
Hallo Peter,

Danke für Deine Rückmeldung!
Hab endlich Zeit gefunden, um ein Update zu machen.

Danke nochmal und viele Grüße!
