### ISSUE TITLE
font-size not changing properly

### ISSUE THREAD

**Issue by TiiFuchs** [vanilla-thunder/bla-tinymce#6]
In our setup it is not possible to set any font-size.
It gets always replaced with `<font size="0">..</font>` no matter which size you actually chose.

Is this a general bug or a bug related to our setup? We did not change the module.

By the way: Is it on purpose, that TinyMCE is configured to use `<font>`-Tags? I think it should use `<span style="..">` tags by default, shouldn't it?

**Comment by sanjeevpande** [comment]
Hi @vanilla-thunder ,
I am using legacyoutput to support flash as well. And I am facing this issue where font size is changed to '0' when fontsize_formats are used in 'px'. Is there any workaround for the same ?

**Comment by vanilla-thunder** [comment]
hello @sanjeevpande 
i finally found the problem:
legacy output plugin expects different parameter syntax for fontsize_formats, than documentation shows:
`8pt=1 10pt=2 12pt=3 14pt=4 18pt=5 24pt=6 36pt=7`
https://github.com/tinymce/tinymce/blob/master/js/tinymce/plugins/legacyoutput/plugin.js#L96

The main reason is, that `<font size="">` accepts absolute values like 1, 2, 3, 4 or relative +1 +2 +3 +4 etc, but values like "13px" seem not to meet up HTML 4.0 standard.

So far, the only quick solution for you would be to configure fontsize_formats as `8px=1 10px=2 12px=3 14px=4 18px=5 24px=6 36px=7` or to drop this config parameter completely.
I found some topics on tinymce forums with exactly the same problem, but the response is alsways like "WTF? why do you want to use legacy output? lol!". I wouldnt expect TinyMCE developers would fix this.

I hope i could help you.

**Comment by sanjeevpande** [comment]
Hi @vanilla-thunder Thanks for the response. We have an application written in flex which is getting migrated to newer web standards. So, for a period of time the demand to support the flex UI will be there.
Having formats as 8px=1 10px=2 12px=3 14px=4 18px=5 24px=6 36px=7 is not helping as we have a little bigger list for fonts. Anyways, I am handling it by creating a listbox button and calling execCommand on select of the option.
